--- #YAML:1.0
name:                Set-IntSpan-Partition
version:             0.01
abstract:            Partition int sets using Set::IntSpan objects
license:             perl
author:              
    - Bjoern Hoehrmann <bjoern@hoehrmann.de>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Set::IntSpan:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
